---
- name: Configure static IP and update /etc/hosts
  hosts: k8s_cluster
  become: yes
  vars:
    netplan_file: /etc/netplan/50-vagrant.yaml

  tasks:
    - name: Set static IP for eth1
      copy:
        dest: "{{ netplan_file }}"
        content: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: true
              eth1:
                dhcp4: false
                addresses:
                  - "{{ ansible_host }}/24"
        mode: "0600"
        backup: yes

    - name: Apply netplan
      command: netplan apply

    - name: Update /etc/hosts with all cluster nodes
      blockinfile:
        path: /etc/hosts
        marker: "# {mark} ANSIBLE MANAGED BLOCK - K8S CLUSTER"
        block: |
          {% for host in groups['k8s_cluster'] %}
          {{ hostvars[host]['ansible_host'] }} {{ host }}
          {% endfor %}
        backup: yes

    - name: Ping test to all cluster nodes
      shell: "ping -c 2 {{ hostvars[item]['ansible_host'] }}"
      register: ping_result
      ignore_errors: yes
      loop: "{{ groups['k8s_cluster'] }}"
      when: hostvars[item]['ansible_host'] != ansible_host

    - name: Show ping test results
      debug:
        var: ping_result.results
