---
- name: Configure static IP addresses and update /etc/hosts
  hosts: k8s_cluster
  become: yes
  vars:
    # 네트워크 구성 변수
    cluster_network:
      subnet: "{{ ansible_host.split('.')[0:3] | join('.') }}"
      gateway: "{{ ansible_host.split('.')[0:3] | join('.') }}.2"
      dns_servers:
        - "{{ ansible_host.split('.')[0:3] | join('.') }}.2"
        - "127.0.0.53"
        - "8.8.8.8" # fallback DNS

  tasks:
    - name: Validate network configuration
      assert:
        that:
          - ansible_host is defined
          - ansible_host | regex_search('^192\.168\.127\.\d+$')
        fail_msg: "Invalid IP address format for {{ inventory_hostname }}: {{ ansible_host }}"
        success_msg: "Valid IP address for {{ inventory_hostname }}: {{ ansible_host }}"

    - name: Check if netplan file exists
      stat:
        path: /etc/netplan/50-vagrant.yaml
      register: netplan_file

    - name: Backup existing netplan configuration
      copy:
        src: /etc/netplan/50-vagrant.yaml
        dest: /etc/netplan/50-vagrant.yaml.backup-{{ ansible_date_time.epoch }}
        remote_src: yes
        backup: yes
      when: netplan_file.stat.exists

    - name: Configure static IP for nodes
      blockinfile:
        path: /etc/netplan/50-vagrant.yaml
        backup: yes
        create: yes
        mode: "0600"
        block: |
          network:
            version: 2
            renderer: networkd
            ethernets:
              eth0:
                dhcp4: true
              eth1:
                dhcp4: false
                addresses:
                  - {{ ansible_host }}/24
                nameservers:
                  addresses:
                    {% for dns in cluster_network.dns_servers %}
                    - "{{ dns }}"
                    {% endfor %}
                routes:
                  - to: 0.0.0.0/0
                    via: "{{ cluster_network.gateway }}"
                    metric: 100
                    on-link: true
      notify:
        - fix netplan permissions
        - validate netplan
        - apply netplan
        - verify connectivity
        - test gateway connectivity
        - test dns resolution

    - name: Update /etc/hosts with all cluster nodes
      blockinfile:
        path: /etc/hosts
        backup: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK - K8S CLUSTER"
        block: |
          {% for host in groups['k8s_cluster'] %}
          {{ hostvars[host]['ansible_host'] }} {{ host }}
          {% endfor %}

  handlers:
    - name: fix netplan permissions
      shell: chmod 600 /etc/netplan/*.yaml
      become: yes

    - name: validate netplan
      command: netplan try --timeout=30
      register: netplan_validate
      failed_when: netplan_validate.rc != 0
      become: yes

    - name: apply netplan
      command: netplan apply
      register: netplan_apply
      failed_when: netplan_apply.rc != 0
      become: yes

    - name: verify connectivity
      wait_for:
        timeout: 10

    - name: test gateway connectivity
      command: ping -c 3 {{ cluster_network.gateway }}
      register: gateway_ping
      ignore_errors: yes

    - name: test dns resolution
      command: nslookup google.com
      register: dns_test
      ignore_errors: yes
